#!/usr/bin/csh 

gemmi mask $1 void.msk
gemmi map2sf void.msk void.mtz Fbulk PHIbulk
gemmi blobs -f Fbulk -p PHIbulk void.mtz $1  >! gemmi_blobs.txt
# voids only count if more than 3 waters fit
awk '$3=="el"{print $5/92}' gemmi_blobs.txt | awk '$1>1' >! void_hist.txt
set nbulk = `awk -v minvoid=3 'NR==1{max=$1} $1>=minvoid{sum+=$1} END{if(max>minvoid)print int(sum)}' void_hist.txt`
