#!/bin/bash 

id=$1
resolution=$2

#--------------------------------------------------------------------------
#  1. Use metatwist to create a solvent density file from guv files:
#--------------------------------------------------------------------------

metatwist --dx $id.O.0.mrc  --species O2-  --odx rho.O.0.mrc  \
    --map rhoelreal --bulkdens 55.55 > metatwist.log
metatwist --dx $id.Na+.0.mrc  --species Na+  --odx rho.Na+.0.mrc  \
    --map rhoelreal --bulkdens 0.1 >> metatwist.log
metatwist --dx $id.Cl-.0.mrc  --species Cl-  --odx rho.Cl-.0.mrc  \
    --map rhoelreal --bulkdens 0.1 >> metatwist.log

metatwist --dx rho.O.0.mrc rho.Na+.0.mrc rho.Cl-.0.mrc \
     --odx solvent.mrc --species none >> metatwist.log

# mv rho.O.0.mrc solvent.mrc

# ================== convert to proper axis order for SFALL
mapmask mapin solvent.mrc mapout a.map <<EOF > metatwist.log
AXIS Z X Y
EOF

# =================== run SFALL
sfall mapin a.map hklout sfalled.mtz <<EOF >> metatwist.log
mode sfcalc mapin
RESO $resolution
EOF

# ==================== convert to rdb file to merge with an sf-dat file:
phenix.mtz.dump -f s -c sfalled.mtz | tr ',' '\t' > sfalled.fmtz

/bin/rm -f sfalled.mtz a.map rho.*.mrc  
