#!/usr/bin/perl -n
#
#   first, read in a pdb file line and unpack
#

if( $_ =~ /^ATOM|^HETATM/){

#  expand to 80+ characters (really hokey version):
chop($_);
$_ .= "                                                                    ";

( $label, $atno, $atname, $alt, $resname, $chainId, $resno, $iCode,
      $x, $y, $z, $occ, $bfact, $element, $charge ) =
    unpack("a6 a5 x a4 a a3 x a a4 a x3 a8 a8 a8 a6 a6 x10 a2 a2",$_);

#
#  do modifications necessary here:
#
$residues_per_chain = 12;

$chainId = "A";
$occ = 0.0625;
if( $resno <=   $residues_per_chain){
  $alt = "A";
} elsif( $resno <= 2*$residues_per_chain){
  $alt = "B";
  $resno -= $residues_per_chain;
} elsif( $resno <= 3*$residues_per_chain){
  $alt = "C";
  $resno -= 2*$residues_per_chain;
} elsif( $resno <= 4*$residues_per_chain){
  $alt = "D";
  $resno -= 3*$residues_per_chain;
} elsif( $resno <= 5*$residues_per_chain){
  $alt = "E";
  $resno -= 4*$residues_per_chain;
} elsif( $resno <= 6*$residues_per_chain){
  $alt = "F";
  $resno -= 5*$residues_per_chain;
} elsif( $resno <= 7*$residues_per_chain){
  $alt = "G";
  $resno -= 6*$residues_per_chain;
} elsif( $resno <= 8*$residues_per_chain){
  $alt = "H";
  $resno -= 7*$residues_per_chain;
} elsif( $resno <= 9*$residues_per_chain){
  $alt = "I";
  $resno -= 8*$residues_per_chain;
} elsif( $resno <= 10*$residues_per_chain){
  $alt = "J";
  $resno -= 9*$residues_per_chain;
} elsif( $resno <= 11*$residues_per_chain){
  $alt = "K";
  $resno -= 10*$residues_per_chain;
} elsif( $resno <= 12*$residues_per_chain){
  $alt = "L";
  $resno -= 11*$residues_per_chain;
} elsif( $resno <= 13*$residues_per_chain){
  $alt = "M";
  $resno -= 12*$residues_per_chain;
} elsif( $resno <= 14*$residues_per_chain){
  $alt = "N";
  $resno -= 13*$residues_per_chain;
} elsif( $resno <= 15*$residues_per_chain){
  $alt = "O";
  $resno -= 14*$residues_per_chain;
} elsif( $resno <= 16*$residues_per_chain){
  $alt = "P";
  $resno -= 15*$residues_per_chain;
}

#
#  write back out
#
printf 
"%6s%5s %-4s%1s%3s %1s%4s%1s   %8.3f%8.3f%8.3f%6.4f%6.2f          %2s%2s\n",
      $label, $atno,$atname,$alt, $resname,$chainId, $resno, $iCode,
        $x,$y,$z, $occ, $bfact, $element, $charge;

}
