#!/bin/bash

in=$(printf "%03d" $1)
let out=$in+1
out=$(printf "%03d" $out)

# ./run_6uc $in

perl -p -e 's/CYX/CYS/;s/HIP/HIS/;s/WAT/HOH/;s/91.458  112.802   73.852/30.486   56.401   73.852/' < alt4_$out.min1.pdb > tmp.pdb

# ========== run refmac with the md-derived solvent and
#            disable the default flat bulk solvent

refmac5 hklin alt4_004.mtz xyzin tmp.pdb xyzout alt4_$out.pdb \
    << EOF > alt4_$out.reflog
LABIN FP=FP SIGFP=SIGFP FPART1=FPART1 PHIP1=PHIP1 FREE=FREE
SOLVENT NO
MAKE NEWLigand Noexit
SCPART 1
NCYC 40
REFI BREF
weight matrix 1
DAMP 0 1 1
monitor few
make link no
make ss no
make hydr y
EOF

# phenix.molprobity tmp.pdb > alt4_$out.molp

/bin/rm -f molprobity* alt4_$out.eff tmp.pdb phenix.log

