#!/bin/bash

in=$1
let out=$in+1
out=$(printf "%03d" $out)

# ./run_6uc $in

perl -p -e 's/CYX/CYS/;s/HID/HIS/;s/WAT/HOH/;' < alt3_023.min1.pdb > tmp.pdb

# ========== run refmac with the md-derived solvent and
#            disable the default flat bulk solvent

refmac5 hklin alt3_023.kh250.mtz xyzin tmp.pdb xyzout alt3_$out.pdb \
    << EOF > alt3_$out.flat.reflog
LABIN FP=FP SIGFP=SIGFP FPART1=FPART1 PHIP1=PHIP1 FREE=FREE
SOLVENT NO
MAKE NEWLigand Noexit
SCPART 1
NCYC 40
REFI BREF ISOT
weight matrix 1
DAMP 0 0.3 0.3
monitor few
make link no
make ss no
make hydr y
make hout y
EOF

# phenix.molprobity tmp.pdb > alt3_$out.molp

/bin/rm -f molprobity* tmp.pdb 

