#!/usr/bin/env perl
#
#   first, read in a pdb file line and unpack
#
$watskip = $nwatskip = 0;

while(<>){

if( $_ =~ /^ATOM|^HETATM/){

#  expand to 80+ characters (really hokey version):
chop($_);
$_ .= "                                                                    ";

( $label, $atno, $atname, $alt, $resname, $chainId, $resno, $iCode,
      $x, $y, $z, $occ, $bfact, $element, $charge ) =
    unpack("a6 a5 x a4 a a3 x a a4 a x3 a8 a8 a8 a6 a6 x10 a2 a2",$_);

#
#  do modifications necessary here:
#

if( $resname eq "HOH" ){
   if( $atname eq " O  " && $bfact > 25. ){ $nwatskip++; $watskip = $resno;  $occ = 0.0; }
   if( $atname eq " H1 " && $resno == $watskip ){ $occ = 0.0; }
   if( $atname eq " H2 " && $resno == $watskip ){ $watskip = 0; $occ = 0.0; }
}

#
#  write back out
#
printf 
"%6s%5s %-4s%1s%3s %1s%4s%1s   %8.3f%8.3f%8.3f%6.2f%6.2f          %2s%2s\n",
      $label, $atno,$atname,$alt, $resname,$chainId, $resno, $iCode,
        $x,$y,$z, $occ, $bfact, $element, $charge;

} else {
   print;
}
}

printf STDERR "set $nwatskip waters to zero occupancy\n";
