#!/bin/bash

#  prepare structure factor files needed for crystallogrphic
#  refinements using msander.
#
#  First input is the pdb-identifier: code assumes that $1-sf.cif
#      and $1.pdb are  available in the current directory
#  Second (optional) input would be names of cif files needed by phenix.refine
#  Third  (optional) input is the space group, only helpful if it is "P1"

id=$1
echo "XrayPrep log file for id $id" > $id-prep.log
ciffiles=$2
spacegroup=$3

#============================================================================
echo "Making input mtz file"
phenix.cif_as_mtz $id-sf.cif  >> $id-prep.log \
     || { echo "  phenix.cif_as_mtz:  Program error"; exit 1; }

echo "Running zero-cycle phenix.refine, filter outliers, possibly convert I to F"
phenix.refine  \
   ${id}.pdb $id-sf.mtz $ciffiles \
   fmodel.xray_data.r_free_flags.generate=True \
   refinement.main.number_of_macro_cycles=0 \
   xray_data.outliers_rejection=True \
   output.write_model_cif_file=False \
   output.overwrite=True \
   output.prefix=cdl output.serial=1 \
   output.write_geo_file=False >> $id-prep.log \
     || { echo "  phenix.refine:  Program error"; exit 1; }

#============================================================================
if [ "x$spacegroup" != "xP1" ]; then

echo "Making the P1-sf.dat file"

phenix.reflection_file_converter cdl_001.mtz --expand_to_p1 \
    --label="F-obs-filtered,SIGF-obs-filtered" --generate_r_free_flags  \
    --r_free_flags_format=ccp4  --mtz=tmp-P1.mtz >> $id-prep.log

#  convert to formatted file:
phenix.mtz.dump -c -f s tmp-P1.mtz  | tr ',' '\t' > $id-P1.fmtz \
     || { echo "  phenix.mtz.dump:  Program error"; exit 1; }

#  make the -sf.dat file needed by xray3:
awk '{printf("%d\t%d\t%d\t%s\t%s\t%d\n", \
      $1,$2,$3,$4,$5, $6>1 ? 1 : $6)}'  $id-P1.fmtz | tail -n +2 > tmp.dat \
     || { echo "  awk:  Program error"; exit 1; }

nrefl=`wc -l tmp.dat | awk '{print $1}'`
echo "$nrefl 0" > $id-P1-sf.dat
cat tmp.dat >> $id-P1-sf.dat

cad hklin1 tmp-P1.mtz hklout $id-P1.mtz <<EOF >> $id-prep.log
LABIN E1=F-obs-filtered E2=SIGF-obs-filtered E3=R-free-flags
LABOUT E1=FOBS E2=SIGFOBS E3=R-free-flags
EOF

fi

#============================================================================
echo "Making the non-P1-sf.dat file"

phenix.reflection_file_converter cdl_001.mtz \
    --label="F-obs-filtered,SIGF-obs-filtered" --generate_r_free_flags  \
    --r_free_flags_format=ccp4  --mtz=tmp.mtz >> $id-prep.log

#  convert to formatted file:
phenix.mtz.dump -c -f s tmp.mtz  | tr ',' '\t' > $id.fmtz \
     || { echo "  phenix.mtz.dump:  Program error"; exit 1; }

#  make the -sf.dat file needed by xray3:
awk '{printf("%d\t%d\t%d\t%s\t%s\t%d\n", \
      $1,$2,$3,$4,$5, $6>1 ? 1 : $6)}'  $id.fmtz | tail -n +2 > tmp.dat \
     || { echo "  awk:  Program error"; exit 1; }

nrefl=`wc -l tmp.dat | awk '{print $1}'`
echo "$nrefl 0" > $id-sf.dat
cat tmp.dat >> $id-sf.dat

cad hklin1 tmp.mtz hklout $id.mtz <<EOF >> $id-prep.log
LABIN E1=F-obs-filtered E2=SIGF-obs-filtered E3=R-free-flags
LABOUT E1=FOBS E2=SIGFOBS E3=R-free-flags
EOF


#============================================================================
echo "Done. Created 3 files:"
echo "   ${id}-sf.dat          Use as reflections_infile"
if [ "x$spacegroup" != "xP1" ]; then
   echo "   ${id}-P1-sf.dat       Use as alternate reflections_infile"
fi
echo "   ${id}-prep.log        Log file: examine this if problems arise"

#============================================================================
# clean up
/bin/rm -f tmp* $id-sf.mtz cdl_data.mtz $id.fmtz $id-P1.fmtz cdl_00* 
