#!/bin/bash

#  Convert a pdb-redo mtz file to formats needed for msander
#  First input is the pdb-identifier: code assumes that ${id}_final.mtz
#      is available in the current directory
#  Second  (optional) input is the space group, only helpful if it is "P1"

id=$1
echo "XrayPrep log file for id $id" > $id-prep.log
spacegroup=$1

#============================================================================
if [ "x$spacegroup" != "xP1" ]; then

echo "Making the P1-sf.dat file"

phenix.reflection_file_converter ${id}_final.mtz --expand_to_p1 \
    --label="FP,SIGFP" --generate_r_free_flags \
    --r_free_flags_format=ccp4  --mtz=tmp-P1.mtz >> $id-prep.log

#  convert to formatted file:
phenix.mtz.dump -c -f s tmp-P1.mtz  | tr ',' '\t' > $id-P1.fmtz \
     || { echo "  phenix.mtz.dump:  Program error"; exit 1; }

#  make the -sf.dat file needed by xray3:
awk '{printf("%d\t%d\t%d\t%s\t%s\t%d\n", \
      $1,$2,$3,$4,$5, $6>1 ? 1 : $6)}'  $id-P1.fmtz | tail -n +2 > tmp.dat \
     || { echo "  awk:  Program error"; exit 1; }

nrefl=`wc -l tmp.dat | awk '{print $1}'`
echo "$nrefl 0" > $id-P1-sf.dat
cat tmp.dat >> $id-P1-sf.dat

fi

#============================================================================
echo "Making the non-P1-sf.dat file"

phenix.reflection_file_converter ${id}_final.mtz \
    --label="FP,SIGFP" --generate_r_free_flags  \
    --r_free_flags_format=ccp4  --mtz=tmp.mtz >> $id-prep.log

#  convert to formatted file:
phenix.mtz.dump -c -f s tmp.mtz  | tr ',' '\t' > $id.fmtz \
     || { echo "  phenix.mtz.dump:  Program error"; exit 1; }

#  make the -sf.dat file needed by xray3:
awk '{printf("%d\t%d\t%d\t%s\t%s\t%d\n", \
      $1,$2,$3,$4,$5, $6>1 ? 1 : $6)}'  $id.fmtz | tail -n +2 > tmp.dat \
     || { echo "  awk:  Program error"; exit 1; }

nrefl=`wc -l tmp.dat | awk '{print $1}'`
echo "$nrefl 0" > $id-sf.dat
cat tmp.dat >> $id-sf.dat


#============================================================================
echo "Done. Created 3 files:"
echo "   ${id}-sf.dat          Use as reflections_infile"
if [ "x$spacegroup" != "xP1" ]; then
   echo "   ${id}-P1-sf.dat       Use as alternate reflections_infile"
fi
echo "   ${id}-prep.log        Log file: examine this if problems arise"

#============================================================================
# clean up
/bin/rm -f tmp* $id.fmtz $id-P1.fmtz
    
